jobs:
  include:
    - name: "Xenial Xerus (16.04), Thrift"
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - libboost-all-dev
            - libssl-dev
            - byacc
            - flex
      before_script:
        - ubuntu_1604/thrift/download.sh
      script:
        - ubuntu_1604/thrift/build.sh
      after_success:
        - ubuntu_1604/thrift/package.sh

